---
- name: Set zero_ui variable
  set_fact:
    zero_ui: zero_ui_default | combine(zero_ui | default({}), recursive=True)

- name: Create directory
  ansible.builtin.file:
    path: "{{ zero_ui.path }}"
    state: directory

- name: Template Docker Compose configuration
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ zero_ui.path }}/docker-compose.yml"

- name: Start ZeroUI
  community.general.docker_compose:
    project_src: "{{ zero_ui.path }}"
    state: present
  become: true
