---
name: Check and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@master

      - name: Publish to Galaxy
        uses: robertdebock/galaxy-action@master
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
